// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxIGl2kVmZym-9tWI2iGHMLZJV5wwEhyw',
    appId: '1:299931036371:web:2099b641d0215c06ca4226',
    messagingSenderId: '299931036371',
    projectId: 'task-manager-6f913',
    authDomain: 'task-manager-6f913.firebaseapp.com',
    storageBucket: 'task-manager-6f913.firebasestorage.app',
    measurementId: 'G-8N9EP858M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC87Nyg9aOy_13yEeP91tcKacqb9-iLCDg',
    appId: '1:299931036371:android:d553502d80e0edf9ca4226',
    messagingSenderId: '299931036371',
    projectId: 'task-manager-6f913',
    storageBucket: 'task-manager-6f913.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh7THX5rWcK57sRh6M3soKonxaGiWiCHo',
    appId: '1:299931036371:ios:3c924a10316f861eca4226',
    messagingSenderId: '299931036371',
    projectId: 'task-manager-6f913',
    storageBucket: 'task-manager-6f913.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh7THX5rWcK57sRh6M3soKonxaGiWiCHo',
    appId: '1:299931036371:ios:3c924a10316f861eca4226',
    messagingSenderId: '299931036371',
    projectId: 'task-manager-6f913',
    storageBucket: 'task-manager-6f913.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxIGl2kVmZym-9tWI2iGHMLZJV5wwEhyw',
    appId: '1:299931036371:web:8b222b7a5cd1d834ca4226',
    messagingSenderId: '299931036371',
    projectId: 'task-manager-6f913',
    authDomain: 'task-manager-6f913.firebaseapp.com',
    storageBucket: 'task-manager-6f913.firebasestorage.app',
    measurementId: 'G-BPFRHV8HHV',
  );
}
